### PR TITLE
Add Website Responsiveness

### PR DESCRIPTION
**Pull request by dennypradipta**
This PR is for adding responsiveness to the website, as referenced in #4 
I added lines of CSS for different devices.

### CODE REVIEW

**Comment by lukicenturi** [comment]
can you assign me please?

**Review by Aditya-shrivastav — COMMENTED** [review]
Resolve the merge conflicts and then send PR again

**Comment by dennypradipta** [comment]
Hey sorry, just got time in Saturday. I'll be updating this PR soon! :)

**Comment by Aditya-shrivastav** [comment]
No Problem, Keep Coding

**Comment by dennypradipta** [comment]
Kindly check the updated PR

**Review by Aditya-shrivastav — APPROVED** [review]

**Comment by Aditya-shrivastav** [comment]
Hey! You still have some merge conflictes left. Sorry for the late response.

**Pull request closed without merging**
