### PR TITLE
change to HTML 5 Semantic, Update index.html and Style.css

### PR DESCRIPTION
**Pull request by nzrmm**
1. Added HTML 5 semantic in index.html

pull2

2. Clean code style.css

pull

3. Update file index.html and Style.css

### CODE REVIEW

**Review by codebloded — APPROVED** [review]

**Comment by surajcool203** [comment]
would u plaese resolve the conflict

**Comment by surajcool203** [comment]
please*

**Comment by nzrmm** [comment]
i have fixed the conflict

**Comment by surajcool203** [comment]
ok ok

**Review by surajcool203 — APPROVED** [review]

**Review by surajcool203 — CHANGES_REQUESTED** [review]
plzz revieqw the commits

**Review by surajcool203 — APPROVED** [review]

**Comment by surajcool203** [comment]
please  resolve the conflict

**Pull request closed without merging**
