### PR TITLE
add scroll bar to the country list

### PR DESCRIPTION
**Pull request by ashvinimore**
closed Dropdown Box #48

### CODE REVIEW

**Comment by surajcool203** [comment]
plzz show the ss of the change

**Review by surajcool203 — APPROVED** [review]

**Comment by ashvinimore** [comment]
Sorry Sir. but ss means ?

**Comment by surajcool203** [comment]
screen shot

**Comment by ashvinimore** [comment]
Screenshot from 2020-10-03 23-05-01
Screenshot from 2020-10-03 23-04-13
Screenshot from 2020-10-03 23-02-04

**Comment by surajcool203** [comment]
great job

**Pull request merged**
