### PR TITLE
change to HTML 5 semantic, rebuild index.html and Style.css

### PR DESCRIPTION
**Pull request by nzrmm**
Hello, i added in your project
1. Change to HTML 5 Semantic
2. Rebuild index.html and Style.css
3. Added responsive in mobile

### CODE REVIEW

**Review by mohitbhata12 — COMMENTED** [review]
@odysseus-me please add the ss of changes you hve made ..and remove conflicts

**Comment by surajcool203** [comment]
resolve the conflict bro

**Comment by nzrmm** [comment]
> @odysseus-me please add the ss of changes you hve made ..and remove conflicts

**Comment by nzrmm** [comment]
Yes, i will fix it latter

**Pull request closed without merging**
