### PR TITLE
Modify README.md file

### PR DESCRIPTION
**Pull request by tanishq-agarwal**
Amend the necessary text and images to make README file more  glaring

### CODE REVIEW

**Comment by surajcool203** [comment]
share the ss

**Comment by tanishq-agarwal** [comment]
Ok

**Comment by tanishq-agarwal** [comment]
Screenshot 2020-10-07 110557
Screenshot 2020-10-07 110851

**Comment by tanishq-agarwal** [comment]
Is it fine?

**Review by mohitbhata12 — APPROVED** [review]

**Comment by surajcool203** [comment]
Bro can u solve the issue there were 2 option showing i thing u didn't give the path correctly

**Comment by tanishq-agarwal** [comment]
looking into it

**Pull request merged**
