### PR TITLE
AM PM issue resolved

### PR DESCRIPTION
**Pull request by Abhishek-7017**
Clock updated

### CODE REVIEW

**Comment by codebloded** [comment]
@Abhishek-7017  resolve the conflicts  then commit

**Review by Isha2103 — COMMENTED** [review]
@Abhishek-7017 You need to resolve the conflicts.

**Comment by Abhishek-7017** [comment]
I will resolve the conflict and the recommit

**Comment by Isha2103** [comment]
@Abhishek-7017 Cool

**Pull request closed without merging**
