### PR TITLE
Fixed issue #8 improved dropdown panel.

### PR DESCRIPTION
**Pull request by atulsingh2030**
Fixed issue #8  improved dropdown panel.
1. Added new countries name in index.html file.
2. Added UTC timezone of updated countries in javascript file.

### CODE REVIEW

**Comment by surajcool203** [comment]
your commit have some conflict plzz check this and submit again

**Comment by atulsingh2030** [comment]
okay i wil check it again.

**Comment by atulsingh2030** [comment]
I have resolved the issues.

**Comment by surajcool203** [comment]
would you plaese provide us the screen shot of your work that you  have done

**Comment by atulsingh2030** [comment]
Screenshot (19)
i have added some countries in index.html file.

**Comment by atulsingh2030** [comment]
Screenshot (20)
Also i have changed the UTC of the added countries in javascript file.

**Comment by atulsingh2030** [comment]
Screenshot (22)
Here is the output in dropdown panel.

**Review by surajcool203 — APPROVED** [review]

**Pull request merged**
